# Generated by Django 5.0.6 on 2024-11-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouschat',
            name='is_admin_response',
            field=models.BooleanField(default=False),
        ),
    ]
