# Generated by Django 5.0.6 on 2024-06-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thepopwinegdrives", "0002_book_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="last_accessed",
            field=models.DateTimeField(),
        ),
    ]
