# Generated by Django 5.0.6 on 2024-06-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thepopwinegdrives", "0003_alter_book_last_accessed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
