# Generated by Django 5.0.6 on 2024-06-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thepopwinegdrives", "0004_scrapedcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_running", models.BooleanField(default=False)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
