# Generated by Django 5.0.6 on 2024-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thepopwinegdrives", "0005_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="task_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
